User.create(name: '近藤（管理者）', email: 'kondo8363@gmail.com', password: 'password', password_confirmation: 'password', admin: 1)

Category.create(category: "トップス")
Category.create(category: "アウター")
Category.create(category: "パンツ")
Category.create(category: "オールインワン")
Category.create(category: "スカート")
Category.create(category: "ワンピース/ドレス")
Category.create(category: "フォーマル")
Category.create(category: "バッグ")
Category.create(category: "シューズ")
Category.create(category: "ファッション雑貨")
Category.create(category: "財布/小物")
Category.create(category: "腕時計")
Category.create(category: "へアクセサリー")
Category.create(category: "アクセサリー")
Category.create(category: "アンダーウェア")
Category.create(category: "レッグウェア")
Category.create(category: "ルームウェア")
Category.create(category: "帽子")